INSERT INTO cpns_soal
(soal_type, soal_kategori_id, soal_pertanyaan, 
soal_jawaban_a, soal_jawaban_b, soal_jawaban_c, soal_jawaban_d, soal_jawaban_e, 
soal_kunci_jawaban, soal_penyelesaian, 
soal_nilai_a, soal_nilai_b, soal_nilai_c, soal_nilai_d, soal_nilai_e, 
soal_nilai_benar, soal_nilai_salah, soal_nilai_kosong) 
VALUES 
('TWK', 1, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0), 
('TWK', 1, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),
('TWK', 1, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TWK', 1, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TWK', 1, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),
('TWK', 2, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0), 
('TWK', 2, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),
('TWK', 2, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TWK', 2, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TWK', 2, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),

('TWK', 3, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0), 
('TWK', 3, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),
('TWK', 3, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TWK', 3, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TWK', 3, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),

('TWK', 4, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0), 
('TWK', 4, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),
('TWK', 4, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TWK', 4, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TWK', 4, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),

('TWK', 5, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0), 
('TWK', 5, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),
('TWK', 5, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TWK', 5, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TWK', 5, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),

('TWK', 7, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0), 
('TWK', 7, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),
('TWK', 7, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TWK', 7, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TWK', 7, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),

('TWK', 8, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0), 
('TWK', 8, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),
('TWK', 8, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TWK', 8, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TWK', 8, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),

('TIU', 9, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0), 
('TIU', 9, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),
('TIU', 9, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TIU', 9, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TIU', 9, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),
('TIU', 10, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0), 
('TIU', 10, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),
('TIU', 10, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TIU', 10, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TIU', 10, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),

('TIU', 11, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0), 
('TIU', 11, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),
('TIU', 11, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TIU', 11, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TIU', 11, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),

('TIU', 12, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0), 
('TIU', 12, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),
('TIU', 12, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TIU', 12, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TIU', 12, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),

('TIU', 13, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0), 
('TIU', 13, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),
('TIU', 13, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TIU', 13, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TIU', 13, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),


('TIU', 14, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0), 
('TIU', 14, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),
('TIU', 14, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TIU', 14, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TIU', 14, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),

('TIU', 15, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0), 
('TIU', 15, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),
('TIU', 15, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TIU', 15, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TIU', 15, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),

('TIU', 16, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0), 
('TIU', 16, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),
('TIU', 16, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TIU', 16, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0) ,
('TIU', 16, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
0,0,0,0,0,
5,0,0),

('TKP', 17, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0), 
('TKP', 17, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),
('TKP', 17, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 17, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 17, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),

('TKP', 18, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0), 
('TKP', 18, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),
('TKP', 18, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 18, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 18, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),

('TKP', 19, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0), 
('TKP', 19, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),
('TKP', 19, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 19, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 19, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),


('TKP', 20, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0), 
('TKP', 20, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),
('TKP', 20, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 20, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 20, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),


('TKP', 21, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0), 
('TKP', 21, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),
('TKP', 21, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 21, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 21, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),

('TKP', 22, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0), 
('TKP', 22, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),
('TKP', 22, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 22, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 22, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),

('TKP', 23, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0), 
('TKP', 23, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),
('TKP', 23, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 23, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 23, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),

('TKP', 24, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0), 
('TKP', 24, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),
('TKP', 24, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 24, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 24, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),

('TKP', 25, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0), 
('TKP', 25, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),
('TKP', 25, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 25, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 25, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),

('TKP', 26, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0), 
('TKP', 26, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),
('TKP', 26, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 26, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 26, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),

('TKP', 27, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0), 
('TKP', 27, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),
('TKP', 27, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 27, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 27, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),

('TKP', 28, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0), 
('TKP', 28, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),
('TKP', 28, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 28, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 28, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),

('TKP', 29, 'Soal satu', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0), 
('TKP', 29, 'Soal dua', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0),
('TKP', 29, 'Soal tiga', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 29, 'Soal empat', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0) ,
('TKP', 29, 'Soal lima', 
'jawaban a', 'jawaban b', 'jawaban c', 'jawaban d', 'jawaban e',
'A', 'penyelesaian',
1,2,3,4,5,
0,0,0);
