INSERT INTO `cpns_soal`
(`soal_type`, `soal_kategori_id`,
 `soal_pertanyaan`,
 `soal_jawaban_a`, `soal_jawaban_b`, `soal_jawaban_c`, `soal_jawaban_d`, `soal_jawaban_e`,
 `soal_kunci_jawaban`,
 `soal_nilai_a`, `soal_nilai_b`, `soal_nilai_c`, `soal_nilai_d`, `soal_nilai_e`,
 `soal_nilai_benar`, `soal_nilai_salah`, `soal_nilai_kosong`) 
 VALUES 
 ('TWK','1',
 'test soal no satu',
 'satu a', 'satu b', 'satu c', 'satu d', 'satu e',
 'A',
 0,0,0,0,0,
 20,0,0),
 ('TWK','1',
 'test soal no dua',
 'dua a', 'dua b', 'dua c', 'dua d', 'dua e',
 'B',
 0,0,0,0,0,
 20,0,0),
 ('TWK','1',
 'test soal no tiga',
 'tiga a', 'tiga b', 'tiga c', 'tiga d', 'tiga e',
 'C',
 0,0,0,0,0,
 20,0,0),
 ('TWK','1',
 'test soal no empat',
 'empat a', 'empat b', 'empat c', 'empat d', 'empat e',
 'D',
 0,0,0,0,0,
 20,0,0),
 ('TWK','1',
 'test soal no lima',
 'lima a', 'lima b', 'lima c', 'lima d', 'lima e',
 'E',
 0,0,0,0,0,
 20,0,0),
 ('TWK','1',
 'test soal no enam',
 'enam a', 'enam b', 'enam c', 'enam d', 'enam e',
 'A',
 0,0,0,0,0,
 20,0,0),
 ('TWK','1',
 'test soal no tujuh',
 'tujuh a', 'tujuh b', 'tujuh c', 'tujuh d', 'tujuh e',
 'B',
 0,0,0,0,0,
 20,0,0),
 ('TWK','1',
 'test soal no delapan',
 'delapan a', 'delapan b', 'delapan c', 'delapan d', 'delapan e',
 'C',
 0,0,0,0,0,
 20,0,0),
 ('TWK','1',
 'test soal no sembilan',
 'sembilan a', 'sembilan b', 'sembilan c', 'sembilan d', 'sembilan e',
 'D',
 0,0,0,0,0,
 20,0,0),
 ('TWK','1',
 'test soal no sepuluh',
 'sepuluh a', 'sepuluh b', 'sepuluh c', 'sepuluh d', 'sepuluh e',
 'E',
 0,0,0,0,0,
 20,0,0),
 ('TWK','1',
 'test soal no sebelas',
 'sebelas a', 'sebelas b', 'sebelas c', 'sebelas d', 'sebelas e',
 'A',
 0,0,0,0,0,
 20,0,0),
 ('TWK','1',
 'test soal no duabelas',
 'duabelas a', 'duabelas b', 'duabelas c', 'duabelas d', 'duabelas e',
 'B',
 0,0,0,0,0,
 20,0,0),
 ('TWK','1',
 'test soal no tigabelas',
 'tigabelas a', 'tigabelas b', 'tigabelas c', 'tigabelas d', 'tigabelas e',
 'C',
 0,0,0,0,0,
 20,0,0),
 ('TWK','1',
 'test soal no empatbelas',
 'empatbelas a', 'empatbelas b', 'empatbelas c', 'empatbelas d', 'empatbelas e',
 'D',
 0,0,0,0,0,
 20,0,0),
 ('TWK','1',
 'test soal no limabelas',
 'limabelas a', 'limabelas b', 'limabelas c', 'limabelas d', 'limabelas e',
 'E',
 0,0,0,0,0,
 20,0,0),
 ('TWK','1',
 'test soal no enambelas',
 'enambelas a', 'enambelas b', 'enambelas c', 'enambelas d', 'enambelas e',
 'A',
 0,0,0,0,0,
 20,0,0),
 ('TWK','1',
 'test soal no tujuhbelas',
 'tujuhbelas a', 'tujuhbelas b', 'tujuhbelas c', 'tujuhbelas d', 'tujuhbelas e',
 'B',
 0,0,0,0,0,
 20,0,0),
 ('TWK','1',
 'test soal no delapanbelas',
 'delapanbelas a', 'delapanbelas b', 'delapanbelas c', 'delapanbelas d', 'delapanbelas e',
 'C',
 0,0,0,0,0,
 20,0,0),
 ('TWK','1',
 'test soal no sembilanbelas',
 'sembilanbelas a', 'sembilanbelas b', 'sembilanbelas c', 'sembilanbelas d', 'sembilanbelas e',
 'D',
 0,0,0,0,0,
 20,0,0),
 ('TWK','1',
 'test soal no duapuluh',
 'duapuluh a', 'duapuluh b', 'duapuluh c', 'duapuluh d', 'duapuluh e',
 'E',
 0,0,0,0,0,
 20,0,0),
 ('TWK','2',
 'test soal no duasatu',
 'duasatu a', 'duasatu b', 'duasatu c', 'duasatu d', 'duasatu e',
 'A',
 0,0,0,0,0,
 20,0,0),
 ('TWK','2',
 'test soal no duadua',
 'duadua a', 'duadua b', 'duadua c', 'duadua d', 'duadua e',
 'B',
 0,0,0,0,0,
 20,0,0),
 ('TWK','2',
 'test soal no duatiga',
 'duatiga a', 'duatiga b', 'duatiga c', 'duatiga d', 'duatiga e',
 'C',
 0,0,0,0,0,
 20,0,0),
 ('TWK','2',
 'test soal no duaempat',
 'duaempat a', 'duaempat b', 'duaempat c', 'duaempat d', 'duaempat e',
 'D',
 0,0,0,0,0,
 20,0,0),
 ('TWK','2',
 'test soal no dualima',
 'dualima a', 'dualima b', 'dualima c', 'dualima d', 'dualima e',
 'E',
 0,0,0,0,0,
 20,0,0),
 ('TWK','2',
 'test soal no duaenam',
 'duaenam a', 'duaenam b', 'duaenam c', 'duaenam d', 'duaenam e',
 'A',
 0,0,0,0,0,
 20,0,0),
 ('TWK','2',
 'test soal no duatujuh',
 'duatujuh a', 'duatujuh b', 'duatujuh c', 'duatujuh d', 'duatujuh e',
 'B',
 0,0,0,0,0,
 20,0,0),
 ('TWK','2',
 'test soal no duadelapan',
 'duadelapan a', 'duadelapan b', 'duadelapan c', 'duadelapan d', 'duadelapan e',
 'C',
 0,0,0,0,0,
 20,0,0),
 ('TWK','2',
 'test soal no duasembilan',
 'duasembilan a', 'duasembilan b', 'duasembilan c', 'duasembilan d', 'duasembilan e',
 'D',
 0,0,0,0,0,
 20,0,0),
 ('TWK','2',
 'test soal no tigapuluh',
 'tigapuluh a', 'tigapuluh b', 'tigapuluh c', 'tigapuluh d', 'tigapuluh e',
 'E',
 0,0,0,0,0,
 20,0,0),
 ('TWK','2',
 'test soal no tigasatu',
 'tigasatu a', 'tigasatu b', 'tigasatu c', 'tigasatu d', 'satu e',
 'A',
 0,0,0,0,0,
 20,0,0),
 ('TWK','2',
 'test soal no tigadua',
 'tigadua a', 'tigadua b', 'tigadua c', 'tigadua d', 'tigadua e',
 'B',
 0,0,0,0,0,
 20,0,0),
 ('TWK','2',
 'test soal no tigatiga',
 'tigatiga a', 'tigatiga b', 'tigatiga c', 'tigatiga d', 'tigatiga e',
 'C',
 0,0,0,0,0,
 20,0,0),
 ('TWK','2',
 'test soal no tigaempat',
 'tigaempat a', 'tigaempat b', 'tigaempat c', 'tigaempat d', 'tigaempat e',
 'D',
 0,0,0,0,0,
 20,0,0),
 ('TWK','2',
 'test soal no tigalima',
 'tigalima a', 'tigalima b', 'tigalima c', 'tigalima d', 'tigalima e',
 'E',
 0,0,0,0,0,
 20,0,0),
 ('TWK','2',
 'test soal no tigaenam',
 'tigaenam a', 'tigaenam b', 'tigaenam c', 'tigaenam d', 'tigaenam e',
 'A',
 0,0,0,0,0,
 20,0,0),
 ('TWK','2',
 'test soal no tigatujuh',
 'tigatujuh a', 'tigatujuh b', 'tigatujuh c', 'tigatujuh d', 'tigatujuh e',
 'B',
 0,0,0,0,0,
 20,0,0),
 ('TWK','2',
 'test soal no tigadelapan',
 'tigadelapan a', 'tigadelapan b', 'tigadelapan c', 'tigadelapan d', 'tigadelapan e',
 'C',
 0,0,0,0,0,
 20,0,0),
 ('TWK','2',
 'test soal no tigasembilan',
 'tigasembilan a', 'tigasembilan b', 'tigasembilan c', 'tigasembilan d', 'tigasembilan e',
 'D',
 0,0,0,0,0,
 20,0,0),
 ('TWK','2',
 'test soal no empatpuluh',
 'empatpuluh a', 'empatpuluh b', 'empatpuluh c', 'empatpuluh d', 'empatpuluh e',
 'E',
 0,0,0,0,0,
 20,0,0),
 
 
 
 
 
 
 
 
 
 ('TIU','3',
 'test soal no satu',
 'satu a', 'satu b', 'satu c', 'satu d', 'satu e',
 'A',
 0,0,0,0,0,
 20,0,0),
 ('TIU','3',
 'test soal no dua',
 'dua a', 'dua b', 'dua c', 'dua d', 'dua e',
 'B',
 0,0,0,0,0,
 20,0,0),
 ('TIU','3',
 'test soal no tiga',
 'tiga a', 'tiga b', 'tiga c', 'tiga d', 'tiga e',
 'C',
 0,0,0,0,0,
 20,0,0),
 ('TIU','3',
 'test soal no empat',
 'empat a', 'empat b', 'empat c', 'empat d', 'empat e',
 'D',
 0,0,0,0,0,
 20,0,0),
 ('TIU','3',
 'test soal no lima',
 'lima a', 'lima b', 'lima c', 'lima d', 'lima e',
 'E',
 0,0,0,0,0,
 20,0,0),
 ('TIU','3',
 'test soal no enam',
 'enam a', 'enam b', 'enam c', 'enam d', 'enam e',
 'A',
 0,0,0,0,0,
 20,0,0),
 ('TIU','3',
 'test soal no tujuh',
 'tujuh a', 'tujuh b', 'tujuh c', 'tujuh d', 'tujuh e',
 'B',
 0,0,0,0,0,
 20,0,0),
 ('TIU','3',
 'test soal no delapan',
 'delapan a', 'delapan b', 'delapan c', 'delapan d', 'delapan e',
 'C',
 0,0,0,0,0,
 20,0,0),
 ('TIU','3',
 'test soal no sembilan',
 'sembilan a', 'sembilan b', 'sembilan c', 'sembilan d', 'sembilan e',
 'D',
 0,0,0,0,0,
 20,0,0),
 ('TIU','3',
 'test soal no sepuluh',
 'sepuluh a', 'sepuluh b', 'sepuluh c', 'sepuluh d', 'sepuluh e',
 'E',
 0,0,0,0,0,
 20,0,0),
 ('TIU','3',
 'test soal no sebelas',
 'sebelas a', 'sebelas b', 'sebelas c', 'sebelas d', 'sebelas e',
 'A',
 0,0,0,0,0,
 20,0,0),
 ('TIU','3',
 'test soal no duabelas',
 'duabelas a', 'duabelas b', 'duabelas c', 'duabelas d', 'duabelas e',
 'B',
 0,0,0,0,0,
 20,0,0),
 ('TIU','3',
 'test soal no tigabelas',
 'tigabelas a', 'tigabelas b', 'tigabelas c', 'tigabelas d', 'tigabelas e',
 'C',
 0,0,0,0,0,
 20,0,0),
 ('TIU','3',
 'test soal no empatbelas',
 'empatbelas a', 'empatbelas b', 'empatbelas c', 'empatbelas d', 'empatbelas e',
 'D',
 0,0,0,0,0,
 20,0,0),
 ('TIU','3',
 'test soal no limabelas',
 'limabelas a', 'limabelas b', 'limabelas c', 'limabelas d', 'limabelas e',
 'E',
 0,0,0,0,0,
 20,0,0),
 ('TIU','3',
 'test soal no enambelas',
 'enambelas a', 'enambelas b', 'enambelas c', 'enambelas d', 'enambelas e',
 'A',
 0,0,0,0,0,
 20,0,0),
 ('TIU','3',
 'test soal no tujuhbelas',
 'tujuhbelas a', 'tujuhbelas b', 'tujuhbelas c', 'tujuhbelas d', 'tujuhbelas e',
 'B',
 0,0,0,0,0,
 20,0,0),
 ('TIU','3',
 'test soal no delapanbelas',
 'delapanbelas a', 'delapanbelas b', 'delapanbelas c', 'delapanbelas d', 'delapanbelas e',
 'C',
 0,0,0,0,0,
 20,0,0),
 ('TIU','3',
 'test soal no sembilanbelas',
 'sembilanbelas a', 'sembilanbelas b', 'sembilanbelas c', 'sembilanbelas d', 'sembilanbelas e',
 'D',
 0,0,0,0,0,
 20,0,0),
 ('TIU','3',
 'test soal no duapuluh',
 'duapuluh a', 'duapuluh b', 'duapuluh c', 'duapuluh d', 'duapuluh e',
 'E',
 0,0,0,0,0,
 20,0,0),
 ('TIU','4',
 'test soal no duasatu',
 'duasatu a', 'duasatu b', 'duasatu c', 'duasatu d', 'duasatu e',
 'A',
 0,0,0,0,0,
 20,0,0),
 ('TIU','4',
 'test soal no duadua',
 'duadua a', 'duadua b', 'duadua c', 'duadua d', 'duadua e',
 'B',
 0,0,0,0,0,
 20,0,0),
 ('TIU','4',
 'test soal no duatiga',
 'duatiga a', 'duatiga b', 'duatiga c', 'duatiga d', 'duatiga e',
 'C',
 0,0,0,0,0,
 20,0,0),
 ('TIU','4',
 'test soal no duaempat',
 'duaempat a', 'duaempat b', 'duaempat c', 'duaempat d', 'duaempat e',
 'D',
 0,0,0,0,0,
 20,0,0),
 ('TIU','4',
 'test soal no dualima',
 'dualima a', 'dualima b', 'dualima c', 'dualima d', 'dualima e',
 'E',
 0,0,0,0,0,
 20,0,0),
 ('TIU','4',
 'test soal no duaenam',
 'duaenam a', 'duaenam b', 'duaenam c', 'duaenam d', 'duaenam e',
 'A',
 0,0,0,0,0,
 20,0,0),
 ('TIU','4',
 'test soal no duatujuh',
 'duatujuh a', 'duatujuh b', 'duatujuh c', 'duatujuh d', 'duatujuh e',
 'B',
 0,0,0,0,0,
 20,0,0),
 ('TIU','4',
 'test soal no duadelapan',
 'duadelapan a', 'duadelapan b', 'duadelapan c', 'duadelapan d', 'duadelapan e',
 'C',
 0,0,0,0,0,
 20,0,0),
 ('TIU','4',
 'test soal no duasembilan',
 'duasembilan a', 'duasembilan b', 'duasembilan c', 'duasembilan d', 'duasembilan e',
 'D',
 0,0,0,0,0,
 20,0,0),
 ('TIU','4',
 'test soal no tigapuluh',
 'tigapuluh a', 'tigapuluh b', 'tigapuluh c', 'tigapuluh d', 'tigapuluh e',
 'E',
 0,0,0,0,0,
 20,0,0),
 ('TIU','4',
 'test soal no tigasatu',
 'tigasatu a', 'tigasatu b', 'tigasatu c', 'tigasatu d', 'satu e',
 'A',
 0,0,0,0,0,
 20,0,0),
 ('TIU','4',
 'test soal no tigadua',
 'tigadua a', 'tigadua b', 'tigadua c', 'tigadua d', 'tigadua e',
 'B',
 0,0,0,0,0,
 20,0,0),
 ('TIU','4',
 'test soal no tigatiga',
 'tigatiga a', 'tigatiga b', 'tigatiga c', 'tigatiga d', 'tigatiga e',
 'C',
 0,0,0,0,0,
 20,0,0),
 ('TIU','4',
 'test soal no tigaempat',
 'tigaempat a', 'tigaempat b', 'tigaempat c', 'tigaempat d', 'tigaempat e',
 'D',
 0,0,0,0,0,
 20,0,0),
 ('TIU','4',
 'test soal no tigalima',
 'tigalima a', 'tigalima b', 'tigalima c', 'tigalima d', 'tigalima e',
 'E',
 0,0,0,0,0,
 20,0,0),
 ('TIU','4',
 'test soal no tigaenam',
 'tigaenam a', 'tigaenam b', 'tigaenam c', 'tigaenam d', 'tigaenam e',
 'A',
 0,0,0,0,0,
 20,0,0),
 ('TIU','4',
 'test soal no tigatujuh',
 'tigatujuh a', 'tigatujuh b', 'tigatujuh c', 'tigatujuh d', 'tigatujuh e',
 'B',
 0,0,0,0,0,
 20,0,0),
 ('TIU','4',
 'test soal no tigadelapan',
 'tigadelapan a', 'tigadelapan b', 'tigadelapan c', 'tigadelapan d', 'tigadelapan e',
 'C',
 0,0,0,0,0,
 20,0,0),
 ('TIU','4',
 'test soal no tigasembilan',
 'tigasembilan a', 'tigasembilan b', 'tigasembilan c', 'tigasembilan d', 'tigasembilan e',
 'D',
 0,0,0,0,0,
 20,0,0),
 ('TIU','4',
 'test soal no empatpuluh',
 'empatpuluh a', 'empatpuluh b', 'empatpuluh c', 'empatpuluh d', 'empatpuluh e',
 'E',
 0,0,0,0,0,
 20,0,0),
 ('TKP','5',
 'test soal no satu',
 'satu a', 'satu b', 'satu c', 'satu d', 'satu e',
 'A',
 5,10,15,20,25,
 0,0,0),
 ('TKP','5',
 'test soal no dua',
 'dua a', 'dua b', 'dua c', 'dua d', 'dua e',
 'B',
 5,10,15,20,25,
 0,0,0),
 ('TKP','5',
 'test soal no tiga',
 'tiga a', 'tiga b', 'tiga c', 'tiga d', 'tiga e',
 'C',
 5,10,15,20,25,
 0,0,0),
 ('TKP','5',
 'test soal no empat',
 'empat a', 'empat b', 'empat c', 'empat d', 'empat e',
 'D',
 5,10,15,20,25,
 0,0,0),
 ('TKP','5',
 'test soal no lima',
 'lima a', 'lima b', 'lima c', 'lima d', 'lima e',
 'E',
 5,10,15,20,25,
 0,0,0),
 ('TKP','5',
 'test soal no enam',
 'enam a', 'enam b', 'enam c', 'enam d', 'enam e',
 'A',
 5,10,15,20,25,
 0,0,0),
 ('TKP','5',
 'test soal no tujuh',
 'tujuh a', 'tujuh b', 'tujuh c', 'tujuh d', 'tujuh e',
 'B',
 5,10,15,20,25,
 0,0,0),
 ('TKP','5',
 'test soal no delapan',
 'delapan a', 'delapan b', 'delapan c', 'delapan d', 'delapan e',
 'C',
 5,10,15,20,25,
 0,0,0),
 ('TKP','5',
 'test soal no sembilan',
 'sembilan a', 'sembilan b', 'sembilan c', 'sembilan d', 'sembilan e',
 'D',
 5,10,15,20,25,
 0,0,0),
 ('TKP','5',
 'test soal no sepuluh',
 'sepuluh a', 'sepuluh b', 'sepuluh c', 'sepuluh d', 'sepuluh e',
 'E',
 5,10,15,20,25,
 0,0,0),
 ('TKP','5',
 'test soal no sebelas',
 'sebelas a', 'sebelas b', 'sebelas c', 'sebelas d', 'sebelas e',
 'A',
 5,10,15,20,25,
 0,0,0),
 ('TKP','5',
 'test soal no duabelas',
 'duabelas a', 'duabelas b', 'duabelas c', 'duabelas d', 'duabelas e',
 'B',
 5,10,15,20,25,
 0,0,0),
 ('TKP','5',
 'test soal no tigabelas',
 'tigabelas a', 'tigabelas b', 'tigabelas c', 'tigabelas d', 'tigabelas e',
 'C',
 5,10,15,20,25,
 0,0,0),
 ('TKP','5',
 'test soal no empatbelas',
 'empatbelas a', 'empatbelas b', 'empatbelas c', 'empatbelas d', 'empatbelas e',
 'D',
 5,10,15,20,25,
 0,0,0),
 ('TKP','5',
 'test soal no limabelas',
 'limabelas a', 'limabelas b', 'limabelas c', 'limabelas d', 'limabelas e',
 'E',
 5,10,15,20,25,
 0,0,0),
 ('TKP','5',
 'test soal no enambelas',
 'enambelas a', 'enambelas b', 'enambelas c', 'enambelas d', 'enambelas e',
 'A',
 5,10,15,20,25,
 0,0,0),
 ('TKP','5',
 'test soal no tujuhbelas',
 'tujuhbelas a', 'tujuhbelas b', 'tujuhbelas c', 'tujuhbelas d', 'tujuhbelas e',
 'B',
 5,10,15,20,25,
 0,0,0),
 ('TKP','5',
 'test soal no delapanbelas',
 'delapanbelas a', 'delapanbelas b', 'delapanbelas c', 'delapanbelas d', 'delapanbelas e',
 'C',
 5,10,15,20,25,
 0,0,0),
 ('TKP','5',
 'test soal no sembilanbelas',
 'sembilanbelas a', 'sembilanbelas b', 'sembilanbelas c', 'sembilanbelas d', 'sembilanbelas e',
 'D',
 5,10,15,20,25,
 0,0,0),
 ('TKP','5',
 'test soal no duapuluh',
 'duapuluh a', 'duapuluh b', 'duapuluh c', 'duapuluh d', 'duapuluh e',
 'E',
 5,10,15,20,25,
 0,0,0),
 ('TKP','6',
 'test soal no duasatu',
 'duasatu a', 'duasatu b', 'duasatu c', 'duasatu d', 'duasatu e',
 'A',
 5,10,15,20,25,
 0,0,0),
 ('TKP','6',
 'test soal no duadua',
 'duadua a', 'duadua b', 'duadua c', 'duadua d', 'duadua e',
 'B',
 5,10,15,20,25,
 0,0,0),
 ('TKP','6',
 'test soal no duatiga',
 'duatiga a', 'duatiga b', 'duatiga c', 'duatiga d', 'duatiga e',
 'C',
 5,10,15,20,25,
 0,0,0),
 ('TKP','6',
 'test soal no duaempat',
 'duaempat a', 'duaempat b', 'duaempat c', 'duaempat d', 'duaempat e',
 'D',
 5,10,15,20,25,
 0,0,0),
 ('TKP','6',
 'test soal no dualima',
 'dualima a', 'dualima b', 'dualima c', 'dualima d', 'dualima e',
 'E',
 5,10,15,20,25,
 0,0,0),
 ('TKP','6',
 'test soal no duaenam',
 'duaenam a', 'duaenam b', 'duaenam c', 'duaenam d', 'duaenam e',
 'A',
 5,10,15,20,25,
 0,0,0),
 ('TKP','6',
 'test soal no duatujuh',
 'duatujuh a', 'duatujuh b', 'duatujuh c', 'duatujuh d', 'duatujuh e',
 'B',
 5,10,15,20,25,
 0,0,0),
 ('TKP','6',
 'test soal no duadelapan',
 'duadelapan a', 'duadelapan b', 'duadelapan c', 'duadelapan d', 'duadelapan e',
 'C',
 5,10,15,20,25,
 0,0,0),
 ('TKP','6',
 'test soal no duasembilan',
 'duasembilan a', 'duasembilan b', 'duasembilan c', 'duasembilan d', 'duasembilan e',
 'D',
 5,10,15,20,25,
 0,0,0),
 ('TKP','6',
 'test soal no tigapuluh',
 'tigapuluh a', 'tigapuluh b', 'tigapuluh c', 'tigapuluh d', 'tigapuluh e',
 'E',
 5,10,15,20,25,
 0,0,0),
 ('TKP','6',
 'test soal no tigasatu',
 'tigasatu a', 'tigasatu b', 'tigasatu c', 'tigasatu d', 'satu e',
 'A',
 5,10,15,20,25,
 0,0,0),
 ('TKP','6',
 'test soal no tigadua',
 'tigadua a', 'tigadua b', 'tigadua c', 'tigadua d', 'tigadua e',
 'B',
 5,10,15,20,25,
 0,0,0),
 ('TKP','6',
 'test soal no tigatiga',
 'tigatiga a', 'tigatiga b', 'tigatiga c', 'tigatiga d', 'tigatiga e',
 'C',
 5,10,15,20,25,
 0,0,0),
 ('TKP','6',
 'test soal no tigaempat',
 'tigaempat a', 'tigaempat b', 'tigaempat c', 'tigaempat d', 'tigaempat e',
 'D',
 5,10,15,20,25,
 0,0,0),
 ('TKP','6',
 'test soal no tigalima',
 'tigalima a', 'tigalima b', 'tigalima c', 'tigalima d', 'tigalima e',
 'E',
 5,10,15,20,25,
 0,0,0),
 ('TKP','6',
 'test soal no tigaenam',
 'tigaenam a', 'tigaenam b', 'tigaenam c', 'tigaenam d', 'tigaenam e',
 'A',
 5,10,15,20,25,
 0,0,0),
 ('TKP','6',
 'test soal no tigatujuh',
 'tigatujuh a', 'tigatujuh b', 'tigatujuh c', 'tigatujuh d', 'tigatujuh e',
 'B',
 5,10,15,20,25,
 0,0,0),
 ('TKP','6',
 'test soal no tigadelapan',
 'tigadelapan a', 'tigadelapan b', 'tigadelapan c', 'tigadelapan d', 'tigadelapan e',
 'C',
 5,10,15,20,25,
 0,0,0),
 ('TKP','6',
 'test soal no tigasembilan',
 'tigasembilan a', 'tigasembilan b', 'tigasembilan c', 'tigasembilan d', 'tigasembilan e',
 'D',
 5,10,15,20,25,
 0,0,0),
 ('TKP','6',
 'test soal no empatpuluh',
 'empatpuluh a', 'empatpuluh b', 'empatpuluh c', 'empatpuluh d', 'empatpuluh e',
 'E',
 5,10,15,20,25,
 0,0,0);